### ISSUE TITLE
can't create /var/lib/homebridge

### ISSUE THREAD

**Issue by h0mesmart** [oznu/boot2docker#1]
Hi There,

I tried to use this iso on a vmware fusion player v. 12.1.0 with a mac os bug sur v. 11.12.1 and I get an error : 
'can't create /var/lib/homebridge'.

The vm settings is Other linux 2.4 Kernel 64 bit, Bridged network, 1 cpu and 1GB Ram. 

Any help would be appreciate
![2021-02-21_11-57-56](https://user-images.githubusercontent.com/64425114/108623059-222af600-743d-11eb-9672-dc113462f8d0.jpg)
.

**Comment by HunterDG** [comment]
Did you attach a virtual hard disk?

**Comment by h0mesmart** [comment]
yes 8GB

**Comment by sbernhardt81** [comment]
change disk controller bus type from SCSI to SATA, that worked for me having the same issue.

**Comment by h0mesmart** [comment]
> change disk controller bus type from SCSI to SATA, that worked for me having the same issue.

That did the trick. thank you so much.

**Comment by oznu** [comment]
Changed the ESXi warning note in the README to a generic note:

> Important: Use a SATA / IDE Controller (SCSI controllers will not work)
